table Candidato
	lineageTag: 5898f84c-b2e9-42c9-bc67-df303b3d07fe

	measure 'Total Leads' = COUNTROWS(Candidato)
		formatString: #,0

	measure 'Leads Gestionados' = CALCULATE([Total Leads], Candidato[Status] <> "Perdido")
		formatString: #,0

	measure 'Leads Perdidos' = CALCULATE([Total Leads], Candidato[Status] = "Perdido")
		formatString: #,0

	measure 'Citas Efectivas' = CALCULATE([Total Leads], Candidato[Status] = "Cita efectiva")
		formatString: #,0

	measure 'Total Matriculas' = CALCULATE([Total Leads], Candidato[Status] IN {"Matriculado", "Matrícula", "Matricula"})
		formatString: #,0

	measure 'Total Inscritos' = CALCULATE([Total Leads], Candidato[Status] IN {"Inscrito", "Inscripción", "Inscripcion"})
		formatString: #,0

	measure 'Total Proyectados' = CALCULATE([Total Leads], Candidato[Status] = "Proyectado")
		formatString: #,0

	measure '% Lead a Cita' = DIVIDE([Citas Efectivas], [Total Leads])
		formatString: 0.0%

	measure '% Lead a Matricula' = DIVIDE([Total Matriculas], [Total Leads])
		formatString: 0.0%

	measure '% Gestionado a Matricula' = DIVIDE([Total Matriculas], [Leads Gestionados])
		formatString: 0.0%

	measure 'Leads YTD' = TOTALYTD([Total Leads], DimFecha[Date])
		formatString: #,0

	measure 'Gestionados YTD' = TOTALYTD([Leads Gestionados], DimFecha[Date])
		formatString: #,0

	measure 'Citas Efectivas YTD' = TOTALYTD([Citas Efectivas], DimFecha[Date])
		formatString: #,0

	measure 'Perdidos YTD' = TOTALYTD([Leads Perdidos], DimFecha[Date])
		formatString: #,0

	measure 'Matriculas YTD' = TOTALYTD([Total Matriculas], DimFecha[Date])
		formatString: #,0

	measure 'Inscritos YTD' = TOTALYTD([Total Inscritos], DimFecha[Date])
		formatString: #,0

	measure 'Proyectados YTD' = TOTALYTD([Total Proyectados], DimFecha[Date])
		formatString: #,0

	measure 'Leads Sin Actividad 7d' = CALCULATE([Leads Gestionados], FILTER(Candidato, ISBLANK(Candidato[LastActivityDate]) || DATEDIFF(Candidato[LastActivityDate], TODAY(), DAY) >= 7))
		formatString: #,0

	measure 'Leads Sin Actividad 30d' = CALCULATE([Leads Gestionados], FILTER(Candidato, ISBLANK(Candidato[LastActivityDate]) || DATEDIFF(Candidato[LastActivityDate], TODAY(), DAY) >= 30))
		formatString: #,0

	measure '% Perdidos' = DIVIDE([Leads Perdidos], [Total Leads])
		formatString: 0.0%

	column Id
		dataType: string
		sourceColumn: Id

	column Status
		dataType: string
		sourceColumn: Status

	column CreatedDate
		dataType: dateTime
		formatString: General Date
		sourceColumn: CreatedDate

	column LastActivityDate
		dataType: dateTime
		formatString: General Date
		sourceColumn: LastActivityDate

	column OwnerId
		dataType: string
		sourceColumn: OwnerId

	column OwnerName
		dataType: string
		sourceColumn: OwnerName

	column UI_Periodo__c
		dataType: string
		sourceColumn: UI_Periodo__c

	column UI_Sede__c
		dataType: string
		sourceColumn: UI_Sede__c

	column UI_UnidadNegocio__c
		dataType: string
		sourceColumn: UI_UnidadNegocio__c

	column UI_CarreraPrimeraOpcionWeb__c
		dataType: string
		sourceColumn: UI_CarreraPrimeraOpcionWeb__c

	column UI_Modalidad__c
		dataType: string
		sourceColumn: UI_Modalidad__c

	column UI_Origen__c
		dataType: string
		sourceColumn: UI_Origen__c

	column UI_Campana__c
		dataType: string
		sourceColumn: UI_Campana__c

	column UI_RazonPerdido__c
		dataType: string
		sourceColumn: UI_RazonPerdido__c

	column UI_SubrazonPerdido__c
		dataType: string
		sourceColumn: UI_SubrazonPerdido__c

	partition Candidato = m
		mode: import
		source = ```
let
    Source = SalesforceSource,
    Lead0 = Source{[Name="Lead"]}[Data],
    EnsureColumn = (tbl as table, output as text, candidates as list) as table =>
        let
            Existing = List.First(List.Select(candidates, each Table.HasColumns(tbl, {_})), null),
            Result = if Table.HasColumns(tbl, {output}) then tbl
                     else if Existing <> null then Table.RenameColumns(tbl, {{Existing, output}})
                     else Table.AddColumn(tbl, output, each null, type nullable text)
        in
            Result,
    Lead1 = EnsureColumn(Lead0, "UI_Periodo__c", {"UI_Periodo__c","Periodo__c","Periodo"}),
    Lead2 = EnsureColumn(Lead1, "UI_Sede__c", {"UI_Sede__c","Sede__c","Sede"}),
    Lead3 = EnsureColumn(Lead2, "UI_UnidadNegocio__c", {"UI_UnidadNegocio__c","UnidadNegocio__c","Unidad_de_Negocio__c","BusinessUnit__c"}),
    Lead4 = EnsureColumn(Lead3, "UI_CarreraPrimeraOpcionWeb__c", {"UI_CarreraPrimeraOpcionWeb__c","UI_CarreraCursar__c","Carrera__c","Carrera"}),
    Lead5 = EnsureColumn(Lead4, "UI_Modalidad__c", {"UI_Modalidad__c","Modalidad__c","Modalidad"}),
    Lead6 = EnsureColumn(Lead5, "UI_Origen__c", {"UI_Origen__c","UI_Fuente__c","Fuente__c","LeadSource"}),
    Lead7 = EnsureColumn(Lead6, "UI_Campana__c", {"UI_Campana__c","Campana__c","CampaignId"}),
    Lead8 = EnsureColumn(Lead7, "UI_RazonPerdido__c", {"UI_RazonPerdido__c","RazonPerdido__c","ReasonLost__c"}),
    Lead9 = EnsureColumn(Lead8, "UI_SubrazonPerdido__c", {"UI_SubrazonPerdido__c","SubrazonPerdido__c"}),
    Keep = Table.SelectColumns(Lead9,{"Id","Status","CreatedDate","LastActivityDate","OwnerId","UI_Periodo__c","UI_Sede__c","UI_UnidadNegocio__c","UI_CarreraPrimeraOpcionWeb__c","UI_Modalidad__c","UI_Origen__c","UI_Campana__c","UI_RazonPerdido__c","UI_SubrazonPerdido__c"}, MissingField.UseNull),
    UsersRaw = try Source{[Name="User"]}[Data] otherwise #table({"Id","Name"},{}),
    Users = Table.SelectColumns(UsersRaw,{"Id","Name"}, MissingField.UseNull),
    Joined = Table.NestedJoin(Keep,{"OwnerId"},Users,{"Id"},"OwnerUser",JoinKind.LeftOuter),
    Expanded = Table.ExpandTableColumn(Joined,"OwnerUser",{"Name"},{"OwnerName"})
in
    Expanded
```
